name: Build CoopNet

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build-linux:
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build]') }}
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Install dependencies
          run: |
            sudo apt update
            sudo apt install -y libcurl4-openssl-dev

        - name: Build CoopNet
          run: make -j$(nproc)

        - name: Upload client library
          uses: actions/upload-artifact@v4
          with:
            name: libcoopnet
            path: ./bin/libcoopnet.a
